### ISSUE TITLE
@Onboarding for desktops is using flutter_keychain which does not support desktop

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#1606]
**Describe the bug**
Onboarding using a desktop (windows in my case) results in error due to flutter_keychain..
Suspect this is due to checking of old method of key storage ?

This issue is seen in the widget but is likely to actually be in at_client_sdk

**To Reproduce**
1. Create Windows desktop app using onboarding widget
2. Try to run then see error

**Expected behavior**
No errors, the flutter_keychain should not be used/called if running on desktop

**Screenshots**
![image](https://user-images.githubusercontent.com/6131216/143319150-98d6fd84-9c79-46f4-bc14-7ee4cfa0d0e5.png)

Logs 
An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:54652/31ZcdINNbvI=/
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method get on channel plugin.appmire.be/flutter_keychain)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
atsign-foundation/at_widgets#1      FlutterKeychain.get (package:flutter_keychain/flutter_keychain.dart:16:7)
<asynchronous suspension>
atsign-foundation/at_widgets#2      KeyChainManager._getAtSignMap (package:at_client_mobile/src/keychain_manager.dart:318:15)
<asynchronous suspension>
atsign-foundation/at_widgets#3      KeyChainManager.checkForValuesInFlutterKeychain (package:at_client_mobile/src/keychain_manager.dart:76:21)
<asynchronous suspension>
atsign-foundation/at_widgets#4      KeyChainManager.getAtSignListFromKeychain (package:at_client_mobile/src/keychain_manager.dart:64:19)
<asynchronous suspension>
atsign-foundation/at_widgets#5      _OnboardingDialogState.initKeyChain (package:catweb/widgets/onboarding_dialog.dart:35:23)
<asynchronous suspension>

**Smartphone (please complete the following information):**
 - Windows 
**Were you using an @‎application when the bug was found?**
  - CATWEB

**Additional context**

**Comment by cconstab** [comment]
Confirmed suspicion, app works moving back to previous bracnh version in pub spec yaml

```
dependency_overrides:  
  at_onboarding_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      path: at_onboarding_flutter
      ref: desktop/development
  at_backupkey_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      path: at_backupkey_flutter
      ref: desktop/development
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client
      ref: c1a01a89da97f439843a31655f2e7fdc4444a381
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client_mobile
      ref: c1a01a89da97f439843a31655f2e7fdc4444a381
      
 ```
