### ISSUE TITLE
at_client-3.0.4 Storage Manager argument issue

### ISSUE THREAD

**Issue by TylerTrott** [atsign-foundation/at_client_sdk#327]
**Describe the bug**
Received this line when trying to Flutter Run:

```
../../../flutter/.pub-cache/hosted/pub.dartlang.org/at_client-3.0.4/lib/src/
    manager/storage_manager.dart:43:23: Error: Too many positional arguments: 1
    allowed, but 2 found.

  Try removing the extra positional arguments.
        await manager.init(currentAtSign, storagePath);
```

**To Reproduce**
1. Run command: `flutter run` on an application

**Expected behavior**
Could not build the application for the simulator.

**Screenshots**
<img width="569" alt="Screen Shot 2021-11-13 at 12 41 15 PM" src="https://user-images.githubusercontent.com/66637408/141658571-25251c49-1403-44f7-a5a9-2af40b0c6d41.png">

**Smartphone (please complete the following information):**
Emulator - Iphone 13 Pro

**Comment by yahu1031** [comment]
@TylerTrott Use `dependency_overrides:` in pubspec.yaml file for time being as follows.

```yaml
dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      ref: trunk
      path: at_client
```
This will resolve the issue for now. And this can be fixed on next release.
