### ISSUE TITLE
Invalid Or Corrupted Pad Block

### ISSUE THREAD

**Issue by kmahon99** [atsign-foundation/at_client_sdk#474]
**Describe the bug**
Adding an base 64 encoded image entry to the local secondary seems to work, but the data that is being returned when I get the image entry is throwing an AT0023: "Invalid argument(s): Invalid or corrupted pad block" error.

**To Reproduce**
1. Create an AtKey: `var key = AtKey()`
2. Assign a Uuid to the key name: `atKey.key = const Uuid().v1();`
3. Set the shared properties to only be shared with my current atSign: `atKey.sharedBy = await clientSDKInstance.getAtSign();
      atKey.sharedWith = await clientSDKInstance.getAtSign();`
4. Upload the image: `await ClientSdkService.getInstance().put(atKey, base64Encode(media));`
5. Fetch all keys in the client, the client will list a set of keys that do indeed include the image's Uuid: `var imageKey = await AtClientManager.getInstance().atClient.getAtKeys();`
6. Attempting to get the associated data throws the above error: `var data = await AtClientManager.getInstance().atClient.get(imageKey);`

**Expected behavior**
The image data is fetched and returned as base 64, which can be decoded and shown in the app.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S20 FE
 - OS: Android One 4.0
 - Browser N/A
 - Version N/A

**Were you using an @‎application when the bug was found?**
Custom app created by me.

**Additional context**
I used to be able to fetch the image, but there was an issue where the secondary sync was not working. Now the sync seems to work, but the client can't get the data.

Logs:
https://cdn.sourceb.in/bins/qgmGMq0LT7/0
https://cdn.sourceb.in/bins/P1HCSyXtHd/0

(Note that the pin exception is part of a separate package and has nothing to do with this issue)

**Comment by gkc** [comment]
Thanks @kmahon99 we will tackle this issue in our next sprint which starts today.

**Comment by yahu1031** [comment]
@kmahon99 I see server timed out and socket exceptions in mine(custom app) as well. But not the corrupted pad block issue. May be specific to atsign?

[Here are logs](https://cdn.sourceb.in/bins/HfmmeXak2v/0) for future investigation.

### Issues found following these steps.

- Sync wasn't working(local data not syncing to remote) - exception while syncing batch
- SocketException
- Server Timeout

### Required info
```yaml
# pubspec.yaml

dependencies:
  at_client_mobile: ^3.1.13
  at_onboarding_flutter: ^4.0.1
  cupertino_icons: ^1.0.4
  dotted_border: ^2.0.0+2
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.4.0
  flutter_qr_reader: ^1.0.5
  freezed_annotation: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  local_auth: ^1.1.11
  lottie: ^1.2.2
  package_info_plus: ^1.4.2
  page_transition: ^2.0.5
  path_provider: ^2.0.9
  permission_handler: ^9.2.0
  provider: ^6.0.2
  secure_application: ^3.8.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.13
  tabler_icons: ^0.0.3
  uuid: ^3.0.6

dependency_overrides:
  at_lookup: ^3.0.14
  at_commons: ^3.0.13
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      ref: trunk
      path: at_client

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  import_sorter: ^4.6.0
  json_serializable: ^6.1.5
```
