### ISSUE TITLE
Out of order notifications

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/at_client_sdk#608]
**Describe the bug**
When using atTalk ([attalk](https://github.com/cconstab/at_talk)) if there is no await on the notification  on line 181 (in branch 'testing-await') then notifications appear out of order. Using the await statement things are in order but VERY slow.

**To Reproduce**
1. First I clone the repo and move to the right branch
2. Then I send a file using unix pipes (see below)
3. with the await on line 181 in place everything arrives in order, without it order is not kept
4. I am pretty sure @gkc and I noticed this in testing a while back and Gary put in a fix ? Not sure why it is happening again/now.

**Expected behavior**
Never get out of order notifications, with await or not on the sending side of the notification.

**Screenshots**
With await in place 

```
cconstab@servalan:~/at_talk$ cat pubspec.yaml | dart bin/at_talk.dart -a "@iot_device02" -t "@iot_device01"
Synching your data....................
name: at_talk
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.17.3 <3.0.0'
dependencies: 
  at_client: ^3.0.3
  at_onboarding_cli: ^1.0.0
  chalkdart: ^2.0.8
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
^C
cconstab@servalan:~/at_talk$

```

```
cconstab@servalan:~/at_talk$ dart bin/at_talk.dart -a "@iot_device01" -t "@iot_device02"
Synching your data..................
@iot_device02: name: at_talk
@iot_device02: description: A sample command-line application.
@iot_device02: version: 1.0.0
@iot_device02: # homepage: https://www.example.com
@iot_device02: environment:
@iot_device02: sdk: '>=2.17.3 <3.0.0'
@iot_device02: dependencies:
@iot_device02: at_client: ^3.0.3
@iot_device02: at_onboarding_cli: ^1.0.0
@iot_device02: chalkdart: ^2.0.8
@iot_device02: dev_dependencies:
@iot_device02: lints: ^1.0.0
@iot_device02: test: ^1.16.0
@iot_device01: ^C
cconstab@servalan:~/at_talk$
```

With await removed

```
cconstab@servalan:~/at_talk$ dart bin/at_talk.dart -a "@iot_device01" -t "@iot_device02"
Synching your data.........................
@iot_device02: at_client: ^3.0.3
@iot_device02: chalkdart: ^2.0.8
@iot_device02: description: A sample command-line application.
@iot_device02: name: at_talk
@iot_device02: lints: ^1.0.0
@iot_device02: # homepage: https://www.example.com
@iot_device02: at_onboarding_cli: ^1.0.0
@iot_device02: sdk: '>=2.17.3 <3.0.0'
@iot_device02: test: ^1.16.0
@iot_device02: environment:
@iot_device02: dependencies:
@iot_device02: version: 1.0.0
@iot_device02: dev_dependencies:
@iot_device01: 
```

Note lines received out of order (e.g. 'name: at_talk'

**Smartphone (please complete the following information):**
`Dart SDK version: 2.17.6 (stable) (Unknown timestamp) on "linux_x64"`

**Were you using an @‎application when the bug was found?**
  - atTalk

**Additional context**
