### ISSUE TITLE
Can't onboard with existing atsign in buzz

### ISSUE THREAD

**Issue by yahu1031** [atsign-foundation/at_client_sdk#656]
**Describe the bug**
I have onboarded with an atsign (`@mangotangostable`). But whenever I restarted my code, I can't auto onboard to the app.

**To Reproduce**
- Clone the latest buzz app from [here](https://github.com/ramtulluri/contacts-app/tree/atbuzz-2.0).
- Run the code and onboard with an atsign.
- Try hot-restarting the app.

**Expected behavior**
The app must auto onboard the app.

**Screenshots**

<img width="867" alt="Screenshot 2022-08-14 at 2 24 23 PM" src="https://user-images.githubusercontent.com/35523357/184529675-3e14c0c7-b506-403b-843a-23cb0c930af0.png">

**Smartphone (please complete the following information):**
 - Device: iPhone12, macOS
 - OS: iOS15.5, macOS12.5

**Were you using an @‎application when the bug was found?**
  - atbuzz

**Additional context**
I thought it was from onboarding but when I called respective methods from the KeychainManager, I got those results mentioned in the image above.

dependencies I use
```yaml
dependencies:
  at_onboarding_flutter: ^4.0.4
  at_lookup: ^3.0.27
  at_sync_ui_flutter: ^1.0.4
  at_commons: ^3.0.9
  at_contact: ^3.0.5
dependency_overrides:
  permission_handler: ^10.0.0
  at_client_mobile:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk
      ref: 0909dcf
      path: at_client_mobile
  at_location_flutter:
    git:
      url: https://github.com/atsign-foundation/at_widgets.git
      ref: toast_fix
      path: at_location_flutter
```
